"""phase 3 race features

Revision ID: 5b61ced19cb7
Revises: c4d9bf81e883
Create Date: 2026-08-09 19:58:12.367156+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "5b61ced19cb7"
down_revision: str | None = "c4d9bf81e883"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "race_features",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.String(length=40), nullable=False),
        sa.Column("horse_id", sa.String(length=40), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=True),
        sa.Column("feature_version", sa.String(length=20), server_default="v1", nullable=False),
        sa.Column("horse_form_score", sa.Float(), nullable=True),
        sa.Column("speed_score", sa.Float(), nullable=True),
        sa.Column("jockey_score", sa.Float(), nullable=True),
        sa.Column("trainer_score", sa.Float(), nullable=True),
        sa.Column("market_score", sa.Float(), nullable=True),
        sa.Column("distance_score", sa.Float(), nullable=True),
        sa.Column("going_score", sa.Float(), nullable=True),
        sa.Column("class_score", sa.Float(), nullable=True),
        sa.Column("horse_runs_before", sa.Integer(), nullable=True),
        sa.Column(
            "features",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.horse_id"],
            name=op.f("fk_race_features_horse_id_horses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["races.race_id"], name=op.f("fk_race_features_race_id_races"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_features")),
        sa.UniqueConstraint("race_id", "horse_id", "feature_version", name="uq_race_features_runner_version"),
    )
    op.create_index("ix_race_features_date", "race_features", ["race_date"], unique=False)
    op.create_index("ix_race_features_horse", "race_features", ["horse_id"], unique=False)
    op.create_index("ix_race_features_race", "race_features", ["race_id"], unique=False)
    op.create_index(
        "ix_race_features_version_date", "race_features", ["feature_version", "race_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_race_features_version_date", table_name="race_features")
    op.drop_index("ix_race_features_race", table_name="race_features")
    op.drop_index("ix_race_features_horse", table_name="race_features")
    op.drop_index("ix_race_features_date", table_name="race_features")
    op.drop_table("race_features")
    # ### end Alembic commands ###
