"""phase 2 racing schema

Revision ID: c4d9bf81e883
Revises:
Create Date: 2026-08-09 19:18:24.388269+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "c4d9bf81e883"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("course_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=60), nullable=True),
        sa.Column("region_code", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("course_id", name=op.f("pk_courses")),
    )
    op.create_index(op.f("ix_courses_name"), "courses", ["name"], unique=False)
    op.create_index(op.f("ix_courses_region_code"), "courses", ["region_code"], unique=False)
    op.create_table(
        "horses",
        sa.Column("horse_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("sex", sa.String(length=30), nullable=True),
        sa.Column("sex_code", sa.String(length=10), nullable=True),
        sa.Column("colour", sa.String(length=40), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("region", sa.String(length=20), nullable=True),
        sa.Column("sire", sa.String(length=120), nullable=True),
        sa.Column("sire_id", sa.String(length=40), nullable=True),
        sa.Column("dam", sa.String(length=120), nullable=True),
        sa.Column("dam_id", sa.String(length=40), nullable=True),
        sa.Column("damsire", sa.String(length=120), nullable=True),
        sa.Column("damsire_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("horse_id", name=op.f("pk_horses")),
    )
    op.create_index(op.f("ix_horses_dam_id"), "horses", ["dam_id"], unique=False)
    op.create_index(op.f("ix_horses_damsire_id"), "horses", ["damsire_id"], unique=False)
    op.create_index(op.f("ix_horses_name"), "horses", ["name"], unique=False)
    op.create_index("ix_horses_name_lower", "horses", ["name"], unique=False)
    op.create_index(op.f("ix_horses_region"), "horses", ["region"], unique=False)
    op.create_index(op.f("ix_horses_sire_id"), "horses", ["sire_id"], unique=False)
    op.create_table(
        "jockeys",
        sa.Column("jockey_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("rides", sa.Integer(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("jockey_id", name=op.f("pk_jockeys")),
    )
    op.create_index(op.f("ix_jockeys_name"), "jockeys", ["name"], unique=False)
    op.create_table(
        "trainers",
        sa.Column("trainer_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("runners_count", sa.Integer(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("strike_rate", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("trainer_id", name=op.f("pk_trainers")),
    )
    op.create_index(op.f("ix_trainers_name"), "trainers", ["name"], unique=False)
    op.create_table(
        "races",
        sa.Column("race_id", sa.String(length=40), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=True),
        sa.Column("off_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("course_id", sa.String(length=40), nullable=True),
        sa.Column("course_name", sa.String(length=120), nullable=True),
        sa.Column("race_name", sa.String(length=255), nullable=True),
        sa.Column("race_class", sa.Integer(), nullable=True),
        sa.Column("race_type", sa.String(length=40), nullable=True),
        sa.Column("pattern", sa.String(length=60), nullable=True),
        sa.Column("age_band", sa.String(length=40), nullable=True),
        sa.Column("rating_band", sa.String(length=40), nullable=True),
        sa.Column("sex_restriction", sa.String(length=40), nullable=True),
        sa.Column("distance_yards", sa.Integer(), nullable=True),
        sa.Column("distance_furlongs", sa.Float(), nullable=True),
        sa.Column("going", sa.String(length=60), nullable=True),
        sa.Column("going_detailed", sa.String(length=255), nullable=True),
        sa.Column("surface", sa.String(length=40), nullable=True),
        sa.Column("jumps", sa.String(length=40), nullable=True),
        sa.Column("weather", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=20), nullable=True),
        sa.Column("prize_money", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("field_size", sa.Integer(), nullable=True),
        sa.Column("winning_time_detail", sa.String(length=120), nullable=True),
        sa.Column("is_abandoned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("has_result", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.course_id"], name=op.f("fk_races_course_id_courses"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("race_id", name=op.f("pk_races")),
    )
    op.create_index(op.f("ix_races_course_id"), "races", ["course_id"], unique=False)
    op.create_index("ix_races_date_class", "races", ["race_date", "race_class"], unique=False)
    op.create_index("ix_races_date_course", "races", ["race_date", "course_id"], unique=False)
    op.create_index(op.f("ix_races_distance_yards"), "races", ["distance_yards"], unique=False)
    op.create_index(op.f("ix_races_going"), "races", ["going"], unique=False)
    op.create_index(op.f("ix_races_has_result"), "races", ["has_result"], unique=False)
    op.create_index(op.f("ix_races_off_time"), "races", ["off_time"], unique=False)
    op.create_index(op.f("ix_races_race_class"), "races", ["race_class"], unique=False)
    op.create_index(op.f("ix_races_race_date"), "races", ["race_date"], unique=False)
    op.create_index(op.f("ix_races_race_type"), "races", ["race_type"], unique=False)
    op.create_index(op.f("ix_races_region"), "races", ["region"], unique=False)
    op.create_table(
        "odds_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.String(length=40), nullable=False),
        sa.Column("horse_id", sa.String(length=40), nullable=False),
        sa.Column("bookmaker", sa.String(length=60), nullable=False),
        sa.Column("decimal_odds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("fractional_odds", sa.String(length=20), nullable=True),
        sa.Column("implied_probability", sa.Float(), nullable=True),
        sa.Column("each_way_places", sa.Integer(), nullable=True),
        sa.Column("each_way_denominator", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.horse_id"],
            name=op.f("fk_odds_history_horse_id_horses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["races.race_id"], name=op.f("fk_odds_history_race_id_races"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_history")),
        sa.UniqueConstraint("race_id", "horse_id", "bookmaker", "recorded_at", name="uq_odds_history_quote"),
    )
    op.create_index(op.f("ix_odds_history_bookmaker"), "odds_history", ["bookmaker"], unique=False)
    op.create_index(
        "ix_odds_history_race_horse_time",
        "odds_history",
        ["race_id", "horse_id", "recorded_at"],
        unique=False,
    )
    op.create_index(op.f("ix_odds_history_race_id"), "odds_history", ["race_id"], unique=False)
    op.create_index(op.f("ix_odds_history_recorded_at"), "odds_history", ["recorded_at"], unique=False)
    op.create_table(
        "race_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.String(length=40), nullable=False),
        sa.Column("horse_id", sa.String(length=40), nullable=False),
        sa.Column("jockey_id", sa.String(length=40), nullable=True),
        sa.Column("trainer_id", sa.String(length=40), nullable=True),
        sa.Column("owner", sa.String(length=160), nullable=True),
        sa.Column("owner_id", sa.String(length=40), nullable=True),
        sa.Column("finishing_position", sa.Integer(), nullable=True),
        sa.Column("finishing_status", sa.String(length=30), server_default="unknown", nullable=False),
        sa.Column("is_winner", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("saddle_cloth", sa.Integer(), nullable=True),
        sa.Column("draw", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("weight_lbs", sa.Integer(), nullable=True),
        sa.Column("headgear", sa.String(length=40), nullable=True),
        sa.Column("starting_price", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("beaten_lengths", sa.Float(), nullable=True),
        sa.Column("overall_beaten_lengths", sa.Float(), nullable=True),
        sa.Column("official_rating", sa.Integer(), nullable=True),
        sa.Column("rpr", sa.Integer(), nullable=True),
        sa.Column("topspeed", sa.Integer(), nullable=True),
        sa.Column("finishing_time", sa.String(length=40), nullable=True),
        sa.Column("prize_won", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.horse_id"],
            name=op.f("fk_race_results_horse_id_horses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jockey_id"],
            ["jockeys.jockey_id"],
            name=op.f("fk_race_results_jockey_id_jockeys"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["races.race_id"], name=op.f("fk_race_results_race_id_races"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.trainer_id"],
            name=op.f("fk_race_results_trainer_id_trainers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_results")),
        sa.UniqueConstraint("race_id", "horse_id", name="uq_race_results_race_horse"),
    )
    op.create_index(
        op.f("ix_race_results_finishing_position"), "race_results", ["finishing_position"], unique=False
    )
    op.create_index(
        "ix_race_results_horse_position", "race_results", ["horse_id", "finishing_position"], unique=False
    )
    op.create_index(op.f("ix_race_results_is_winner"), "race_results", ["is_winner"], unique=False)
    op.create_index(
        "ix_race_results_jockey", "race_results", ["jockey_id", "finishing_position"], unique=False
    )
    op.create_index(op.f("ix_race_results_race_id"), "race_results", ["race_id"], unique=False)
    op.create_index(
        "ix_race_results_trainer", "race_results", ["trainer_id", "finishing_position"], unique=False
    )
    op.create_table(
        "race_runners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.String(length=40), nullable=False),
        sa.Column("horse_id", sa.String(length=40), nullable=False),
        sa.Column("jockey_id", sa.String(length=40), nullable=True),
        sa.Column("trainer_id", sa.String(length=40), nullable=True),
        sa.Column("owner", sa.String(length=160), nullable=True),
        sa.Column("owner_id", sa.String(length=40), nullable=True),
        sa.Column("saddle_cloth", sa.Integer(), nullable=True),
        sa.Column("draw", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("weight_lbs", sa.Integer(), nullable=True),
        sa.Column("headgear", sa.String(length=40), nullable=True),
        sa.Column("official_rating", sa.Integer(), nullable=True),
        sa.Column("rpr", sa.Integer(), nullable=True),
        sa.Column("topspeed", sa.Integer(), nullable=True),
        sa.Column("days_since_last_run", sa.Integer(), nullable=True),
        sa.Column("form", sa.String(length=60), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.horse_id"],
            name=op.f("fk_race_runners_horse_id_horses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jockey_id"],
            ["jockeys.jockey_id"],
            name=op.f("fk_race_runners_jockey_id_jockeys"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["races.race_id"], name=op.f("fk_race_runners_race_id_races"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.trainer_id"],
            name=op.f("fk_race_runners_trainer_id_trainers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_runners")),
        sa.UniqueConstraint("race_id", "horse_id", name="uq_race_runners_race_horse"),
    )
    op.create_index("ix_race_runners_horse_race", "race_runners", ["horse_id", "race_id"], unique=False)
    op.create_index(op.f("ix_race_runners_jockey_id"), "race_runners", ["jockey_id"], unique=False)
    op.create_index(op.f("ix_race_runners_race_id"), "race_runners", ["race_id"], unique=False)
    op.create_index(op.f("ix_race_runners_trainer_id"), "race_runners", ["trainer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_race_runners_trainer_id"), table_name="race_runners")
    op.drop_index(op.f("ix_race_runners_race_id"), table_name="race_runners")
    op.drop_index(op.f("ix_race_runners_jockey_id"), table_name="race_runners")
    op.drop_index("ix_race_runners_horse_race", table_name="race_runners")
    op.drop_table("race_runners")
    op.drop_index("ix_race_results_trainer", table_name="race_results")
    op.drop_index(op.f("ix_race_results_race_id"), table_name="race_results")
    op.drop_index("ix_race_results_jockey", table_name="race_results")
    op.drop_index(op.f("ix_race_results_is_winner"), table_name="race_results")
    op.drop_index("ix_race_results_horse_position", table_name="race_results")
    op.drop_index(op.f("ix_race_results_finishing_position"), table_name="race_results")
    op.drop_table("race_results")
    op.drop_index(op.f("ix_odds_history_recorded_at"), table_name="odds_history")
    op.drop_index(op.f("ix_odds_history_race_id"), table_name="odds_history")
    op.drop_index("ix_odds_history_race_horse_time", table_name="odds_history")
    op.drop_index(op.f("ix_odds_history_bookmaker"), table_name="odds_history")
    op.drop_table("odds_history")
    op.drop_index(op.f("ix_races_region"), table_name="races")
    op.drop_index(op.f("ix_races_race_type"), table_name="races")
    op.drop_index(op.f("ix_races_race_date"), table_name="races")
    op.drop_index(op.f("ix_races_race_class"), table_name="races")
    op.drop_index(op.f("ix_races_off_time"), table_name="races")
    op.drop_index(op.f("ix_races_has_result"), table_name="races")
    op.drop_index(op.f("ix_races_going"), table_name="races")
    op.drop_index(op.f("ix_races_distance_yards"), table_name="races")
    op.drop_index("ix_races_date_course", table_name="races")
    op.drop_index("ix_races_date_class", table_name="races")
    op.drop_index(op.f("ix_races_course_id"), table_name="races")
    op.drop_table("races")
    op.drop_index(op.f("ix_trainers_name"), table_name="trainers")
    op.drop_table("trainers")
    op.drop_index(op.f("ix_jockeys_name"), table_name="jockeys")
    op.drop_table("jockeys")
    op.drop_index(op.f("ix_horses_sire_id"), table_name="horses")
    op.drop_index(op.f("ix_horses_region"), table_name="horses")
    op.drop_index("ix_horses_name_lower", table_name="horses")
    op.drop_index(op.f("ix_horses_name"), table_name="horses")
    op.drop_index(op.f("ix_horses_damsire_id"), table_name="horses")
    op.drop_index(op.f("ix_horses_dam_id"), table_name="horses")
    op.drop_table("horses")
    op.drop_index(op.f("ix_courses_region_code"), table_name="courses")
    op.drop_index(op.f("ix_courses_name"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
