"""phase 5 bet ledger

Revision ID: 6df1c06be46b
Revises: 5b61ced19cb7
Create Date: 2026-08-09 21:29:51.183235+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6df1c06be46b"
down_revision: str | None = "5b61ced19cb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet_ledger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("strategy", sa.String(length=60), nullable=False),
        sa.Column("model_version", sa.String(length=60), nullable=True),
        sa.Column("race_id", sa.String(length=40), nullable=False),
        sa.Column("horse_id", sa.String(length=40), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_probability", sa.Float(), nullable=True),
        sa.Column("market_probability", sa.Float(), nullable=True),
        sa.Column("edge", sa.Float(), nullable=True),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("observed_odds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("odds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("stake", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("stake_constraint", sa.String(length=40), nullable=True),
        sa.Column("won", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("finishing_position", sa.Integer(), nullable=True),
        sa.Column("profit_loss", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("bankroll_after", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["horse_id"], ["horses.horse_id"], name=op.f("fk_bet_ledger_horse_id_horses"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["race_id"], ["races.race_id"], name=op.f("fk_bet_ledger_race_id_races"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bet_ledger")),
    )
    op.create_index("ix_bet_ledger_race", "bet_ledger", ["race_id"], unique=False)
    op.create_index(op.f("ix_bet_ledger_race_date"), "bet_ledger", ["race_date"], unique=False)
    op.create_index("ix_bet_ledger_run_date", "bet_ledger", ["run_id", "race_date"], unique=False)
    op.create_index(op.f("ix_bet_ledger_run_id"), "bet_ledger", ["run_id"], unique=False)
    op.create_index("ix_bet_ledger_strategy", "bet_ledger", ["strategy"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bet_ledger_strategy", table_name="bet_ledger")
    op.drop_index(op.f("ix_bet_ledger_run_id"), table_name="bet_ledger")
    op.drop_index("ix_bet_ledger_run_date", table_name="bet_ledger")
    op.drop_index(op.f("ix_bet_ledger_race_date"), table_name="bet_ledger")
    op.drop_index("ix_bet_ledger_race", table_name="bet_ledger")
    op.drop_table("bet_ledger")
    # ### end Alembic commands ###
